### PR TITLE
The voice of god

### PR DESCRIPTION
**Pull request by DEATHB4DEFEAT**
# About the PR

Adds the Voice Of God component,

- Plays a sound of choice when a chat message is sent
- Optionally accents the message, ALL CAPS
- Uses an Loc of choice to wrap a message with an optional color of choice

Was originally to remake a funny component from 13, but I decided this could be a more multipurpose system, if requested I'll rename it.

# Media

[video](https://user-images.githubusercontent.com/77995199/229401783-290240ab-f526-4506-bc4e-68b37ad2024e.mp4)

### CODE REVIEW

**Review by Pspritechologist — COMMENTED** [review]
I'd be curious of your intended use cases of something like this.

**Comment by DEATHB4DEFEAT** [comment]
memery, maybe some mobs in the future

**Comment by Pspritechologist** [comment]
As far as I can tell, this system _primarily_ allows for two things; Playing a specified sound when you speak, and colouring your chat. They're a couple of other things like the custom wrap and accent, but that's the meat.

I feel like this is two individual systems merged into one, as playing a sound when sending a message is already in the game and any modifications to it should probably just go through the existing system (or a better one), and coloured text has much more general applications that could be considered outside of this, which should be made into it's own system (or segment of a system) for more general purpose usability.

**Review by Pspritechologist — COMMENTED** [review]
As far as I can tell, this system _primarily_ allows for two things; Playing a specified sound when you speak, and colouring your chat. They're a couple of other things like the custom wrap and accent, but that's the meat.

I feel like this is two individual systems merged into one, as playing a sound when sending a message is already in the game and any modifications to it should probably just go through the existing system (or a better one), and coloured text has much more general applications that could be considered outside of this, which should be made into it's own system (or segment of a system) for more general purpose usability.

**Comment by DEATHB4DEFEAT** [comment]
> playing a sound when sending a message is already in the game and any modifications to it should probably just go through the existing system (or a better one)

> memery

can't modify the SpeechComponent SpeechSounds to whatever sound, must be a SpeechSoundsPrototype

**Pull request closed without merging**
