### PR TITLE
Changes to the HoP suit helmet sprite

### PR DESCRIPTION
**Pull request by SomeCabbage**
# Description
Changes the sprite of the HoP hardsuit helmet to look more like the hop's hat

# Media
See files changed.

# Changelog

:cl:
- tweak: HoP's hardsuit helmet now looks more like the hat and less boring

### CODE REVIEW

**Comment by DEATHB4DEFEAT** [comment]
Hopsuithelmetchange

**Comment by DEATHB4DEFEAT** [comment]
> # Media
> See files changed

[Thank you for blinding me, GitHub](https://img.simplemodbot.tk/khH1ZJkcMcnF.png)
image alt text

**Comment by DEATHB4DEFEAT** [comment]
is this a draft?

**Comment by DEATHB4DEFEAT** [comment]
image

**Review by DEATHB4DEFEAT — APPROVED** [review]

**Comment by SomeCabbage** [comment]
> image

yeah I dunno why it's like that

**Comment by Pspritechologist** [comment]
> > image
> 
> yeah I dunno why it's like that

That's just because "binary files" (as I believe they're called) don't count as line changes.

**Pull request merged**
