### PR TITLE
Inventory fixes

### PR DESCRIPTION
**Pull request by SomeCabbage**
# Description
Fixes the Admin Ghost inventory not working properly.
Fixes the cuffs sprite error on punpun
Makes it so that ghosts can now have hats forced onto them by aghosts. To make sure the hats are visible, the ghost transparency has been toned down a little.

### CODE REVIEW

**Comment by DEATHB4DEFEAT** [comment]
:trollface:

**Review by DEATHB4DEFEAT — APPROVED** [review]

**Comment by SomeCabbage** [comment]
hehe

**Comment by Pspritechologist** [comment]
Mayhaps consider making the ghost sprite itself transparent, and then removing transparency altogether?

In addition, if you can make the sprite layers themselves unshaded, that would fix things not being visible in the dark. That'd be appreciated.

**Comment by SomeCabbage** [comment]
cant seem to make hats unshaded but otherwise this should be good to merge

**Review by Pspritechologist — APPROVED** [review]

**Pull request merged**
