### PR TITLE
Update to OhioStation

### PR DESCRIPTION
**Pull request by JasperStingtail**
# Description

Changed some parts of OhioStation
# TODO

# Media

# Changelog

:cl:
-fix: Fixed cargo spacing
-fix: Fixed an unpowered engineering door 
-fix: Fixed epi scanning modules to have a vessel machine
-fix: Fixed cloning to work now
-add: Added a door in epi hallways for ease of access
-add: Added more directional signs
-add: Reluctantly added mouse timed spawners
-add: Added bottle of nothing to clown/mime room
-add: Added navigational decals
-change: changed firelocks to be glass firelocks
-fix: East and west evac have been fixed to dock properly

### CODE REVIEW

**Comment by JasperStingtail** [comment]
Added some navigational markers
image

**Comment by JasperStingtail** [comment]
Changed to glass firelocks
East Evac docking fixed

**Comment by JasperStingtail** [comment]
Made the west evac area work now. Git still confuses me

**Comment by JasperStingtail** [comment]
Added decoration in bar
Added cleanable dirt decals
Added chairs at evacs and arrivals

**Review by Pspritechologist — APPROVED** [review]

**Pull request merged**
