### PR TITLE
Removes Chemical Medipen and Adds Armor to Sec Biosuit

### PR DESCRIPTION
**Pull request by BlitzGunner225**
## About the PR 

I've got 2 small changes. 
The first is to give the Sec Biosuit armor due to the sprite having armor. This makes sense due to sec needing some armor but shouldn't really cause everyone to use them all the time as there is still a slowdown from the suit. 
The second change is removing the Chemical Medipen from the Medical vendor, essentially from the entire game unless spawned in from admins. It was essentially a better Hypnopen that anyone could get with ease and abuse as a very strong weapon.

**Changelog**

:cl:
- add: Added armor to Sec Biosuit
- remove: Removed Chemical Medipen

### CODE REVIEW

**Comment by DEATHB4DEFEAT** [comment]
an odd combination of things to have together

**Comment by DEATHB4DEFEAT** [comment]
also this does not entirely remove chemipens disliked functionality

**Comment by Pspritechologist** [comment]
This PR just adds an armour value to the Sec biosuits? They're still unused in every portion of the game.
I'd need to know they values are balanced, what'd you compare them to? They should probably slow you down a lot, to give the "exterminator" vibe. In that vein, I'd prefer it give slashing and heat resistance, rather than piercing, to make it effective against monsters like a bio-exo-suit.

**Comment by BlitzGunner225** [comment]
I kinda just grouped em together but I could probably seperate em because the chem medipens getting removed from vendors, which should essentially remove them from game unless spawned in by admins, has some mapping problems or something.

**Pull request closed without merging**
