### PR TITLE
3 minute roundend

### PR DESCRIPTION
**Pull request by DEATHB4DEFEAT**
# Description

Makes the time at Central Command 3 minutes instead of 1. (I'd say something like 5, but this is meant for discussion)

# Changelog

:cl: DEATHB4DEFEAT
- tweak: Central Command has allowed crew members to stay on the CC station for 3 minutes instead of only 1 before teleporting them to cryo!

### CODE REVIEW

**Comment by DEATHB4DEFEAT** [comment]
should be a cvar, can probably make a PR for that upstream

**Comment by DEATHB4DEFEAT** [comment]
CC map needs improvement

**Comment by Pspritechologist** [comment]
I just don't think this is a good move at the moment,. We already make people wait for a long shuttle arrival, a long shuttle idle, and a long shuttle trip. Making them THEN wait, at CC, doing nothing seems just plain rude.
I'm happy to hear out some ideas for what a good post-round might look like, but at the moment, it's just debriefing time to me.

**Comment by DEATHB4DEFEAT** [comment]
less reason for EORG, there's time to explore

**Comment by Pspritechologist** [comment]
Explore what though? The same empty, dull map with four Captain's lockers? CC is low effort, and there's nothing interesting on there. I think it'll just result in _more_ annoying EORG.

**Comment by DEATHB4DEFEAT** [comment]
> CC map needs improvement

**Comment by Pspritechologist** [comment]
Sure, but that's no reason to change this _now_.

Close this for now, then?

**Pull request closed without merging**
