### PR TITLE
[Species] Plasmaman species

### LINKED ISSUE #5: Plasmaman

### PR DESCRIPTION
**Pull request by DEATHB4DEFEAT**
Add Plasmamen species.

### CODE REVIEW

**Review by CharcoalGungan — APPROVED** [review]
Looks fine to me : )

**Comment by Pspritechologist** [comment]
Let's leave this for now until I'm in a state to actually check them out.
A lot more I think will need to be done to facilitate them in the game, like setting up maps for refilling their tanks and what have you.

**Comment by DEATHB4DEFEAT** [comment]
should merge this, no extra changes, with conflicts :trollface:

**Comment by DEATHB4DEFEAT** [comment]
Has been sitting derelict for a while, we need to figure out what to do with this.

**Pull request closed without merging**
