### PR TITLE
Character Loadouts

### PR DESCRIPTION
**Pull request by DEATHB4DEFEAT**
# Character Loadouts

## Description

A tab in the HumanoidProfile editor with more tabs for categorization used to select items (toys/clothing) that you wish to spawn with when you join the round. Each item has an amount of points it takes, you have a default of 9(?) points to spend.

## Checklist

- [x] LoadoutPrototype
- [x] Debug Prototypes
- [x] More example prototypes
- [x] Release Prototypes
- [x] Why do we need 2 variables to categorize it?
---
- [x] Character editor tab
- [x] Locale
- [x] Loadout tabs, autogenerated via prototypes
- [x] Fix traits and loadouts unrendering the preview
- [x] Better solution for reloading UI instead of saving
- [ ] Scrolling SubTab bar
- [x] Scrolling loadout list
- [x] Icons in the list
---
- [x] Points system
- [x] Job whitelist
- [x] Show job whitelist in tooltip
---
- [x] Database
- [x] Save loadout preferences
---
- [x] Give items on join, in bag (on floor if no bag)
- [x] Exclusive option, tries to equip the item wherever it can

### CODE REVIEW

**Comment by DEATHB4DEFEAT** [comment]
Ready for review, I need a list of items to be added as loadouts so **don't merge this yet**!

**Review by Pspritechologist — CHANGES_REQUESTED** [review]
Alright, this is a _very_ cool step in the right direction. Gonna be very cool once we've got different items and everything. I like that the categories are so fluidly adjustable, it'll make it easy to add a new one for one set of items if it were to make sense.
That being said, I'm a little confused about the formatting of it. You need to specify number and name for the category for each item that's in it? That could probably be cleaned up a little bit.
I assume whitelist by role is something we could do? A few more test prototypes like the one you have, just to show off some of the useful white/blacklists you can do would be great. For instance, by role, or even by trait (component), so that we could have different pairs of eyeglasses for instance.

It's awesome that you got equipping to an inventory to work (we may want to integrate that more globally), but the next big thing I'd say would be to test if the item can be equipped to a certain slot, and if not, put in the bag. Ideally, it'd go Slot > Bag > Hands. Being able to specify whether the item is an override or not would also be great, for instance for underwear, or variant jumpsuits like Paramedic, or Assistant.

Being able to make things mutually exclusive through some way, maybe just a "group" tag on the prototypes, or as a true/false by category (so that jumpsuits can be exclusive, but not Misc.) that would only allow you to pick one jumpsuit would be very nice. Starting with multiples of the same clothing type in 13 as a new player was always very disorienting.
Overall, really great work.


Also, once we have money, first thing we should do is look into someone for front end :P
It's a skill that doesn't come for free, and damn do we need it.

**Comment by Pspritechologist** [comment]
Oh, and if you could work out whatever that same issue with traits is that's causing the player to stop rendering, it's a non-urgent but annoying bug.
I assume we won't be getting loadouts to render on the character? :P

**Comment by DEATHB4DEFEAT** [comment]
> test if the item can be equipped to a certain slot, and if not, put in the bag. Ideally, it'd go Slot > Bag > Hands.

I thought of doing this, but didn't really like it. I thought of this system as some extra carry-on you take with you on the flight to the station, since I also want to allow some toys to be accessible via loadouts.

Clothing overrides would be something for the alternate job titles.

**Comment by DEATHB4DEFEAT** [comment]
> That being said, I'm a little confused about the formatting of it. You need to specify number and name for the category for each item that's in it? That could probably be cleaned up a little bit.

I just have this how it is just to get it to work, other methods i've tried with a single yml variable weren't working.
I did plan on fixing this up.

**Comment by DEATHB4DEFEAT** [comment]
> or even by trait (component), so that we could have different pairs of eyeglasses for instance.

This is already doable with the whitelist.

**Comment by DEATHB4DEFEAT** [comment]
> Being able to make things mutually exclusive through some way, maybe just a "group" tag on the prototypes, or as a true/false by category (so that jumpsuits can be exclusive, but not Misc.) that would only allow you to pick one jumpsuit would be very nice.

I don't see much point in doing this, why wouldn't you want to spend all 9 points on jumpsuits? :P

**Comment by DEATHB4DEFEAT** [comment]
> Starting with multiples of the same clothing type in 13 as a new player was always very disorienting.

I doubt a new player would see this option, and if they did I don't think it would be too confusing.

**Comment by Pspritechologist** [comment]
> > Being able to make things mutually exclusive through some way, maybe just a "group" tag on the prototypes, or as a true/false by category (so that jumpsuits can be exclusive, but not Misc.) that would only allow you to pick one jumpsuit would be very nice.
> 
> I don't see much point in doing this, why wouldn't you want to spend all 9 points on jumpsuits? :P

Although I agree this is pretty low priority if anything, I do think it would be a nice touch for the system. That said, I also see the benefit of not restricting it. We can leave it to further discussion, it doesn't need to be implemented right away, if ever.


> > or even by trait (component), so that we could have different pairs of eyeglasses for instance.
> 
> This is already doable with the whitelist.

I figured! :D Having some examples of it done would simply be convenient for copy pasting.
A pair of eyeglasses that are free if you have nearsightedness, and then variants that cost points :0


> > test if the item can be equipped to a certain slot, and if not, put in the bag. Ideally, it'd go Slot > Bag > Hands.
> 
> I thought of doing this, but didn't really like it. I thought of this system as some extra carry-on you take with you on the flight to the station, since I also want to allow some toys to be accessible via loadouts.
> 
> Clothing overrides would be something for the alternate job titles.

Although I see your point to a certain extent, we wouldn't want every variant outfit to be a new role title. For example, a Janitor's hat vs a Janitor's hat flipped, being able to pick would be nice, and starting with both is awkward. One thing I'd love to avoid is that 13 effect where the halls are littered with grey jumpsuits because everyone spawns with them and chucks them away.
Shouldn't be hard to implement, right? If override on the item then get item already in slot, if there, delete it.

As for the carryon idea, that's perfectly fine, and works great for items, spare outfits, etc., but for the actual outfit you intend to wear all shift, it does make more sense to show up in it.

**Comment by Pspritechologist** [comment]
Categories being a seperate .yml is probably worth at least considering. It would make them a little more firm, make it easier to specify details about the category if there are any, and would avoid the issue of specifying more than one detail per item (I.E., the detail of which one it's in.
Probably at least worth considering, although I do kinda like how it's handled now :P.

**Comment by DEATHB4DEFEAT** [comment]
> Categories being a seperate .yml is probably worth at least considering. It would make them a little more firm, make it easier to specify details about the category if there are any, and would avoid the issue of specifying more than one detail per item (I.E., the detail of which one it's in. Probably at least worth considering, although I do kinda like how it's handled now :P.

I think having the categories specified via another prototype would go even farther from my intentions than the current one, adding another unnecessary layer of difficulty to adding new things.
My intentions being to have the loadout prototype specify which category it belongs in, the code taking that category into a de-duplicated list, and assigning it a number, then filtering each loadout into those categories.

**Comment by DEATHB4DEFEAT** [comment]
Oh boy, review time! Everything on the checklist has been completed.

**Comment by Pspritechologist** [comment]
@DEATHB4DEFEAT Finish the UI tweaks, order the equip list with exclusive items being first, and do a final check over the items available. Should be good to merge at that point.

**Pull request merged**
