### PR TITLE
Give chemipens a large use delay

### PR DESCRIPTION
**Pull request by DEATHB4DEFEAT**
# Description

add big delay so they aren't just a great alternative to the hypospray

# Changelog

:cl:
- tweak: Chemical medipens (and all other forms of it) have a large reuse delay depending on their volume.

### CODE REVIEW

**Comment by ashkitten** [comment]
why not make the chemmaster needed to fill them? then they get labels, too

**Comment by DEATHB4DEFEAT** [comment]
hand labeler

**Comment by ashkitten** [comment]
sure but you could fill a bottle and hand label it too and it's easier in the chemmaster. i would expect them to be filled from the chemmaster since there's no way to draw liquid with a medipen. then you don't need to have an awkward use timer in order to nerf them to essentially the same effect

**Comment by SomeCabbage** [comment]
is the delay in seconds?

**Comment by DEATHB4DEFEAT** [comment]
yes

**Comment by SomeCabbage** [comment]
oh...

**Comment by SomeCabbage** [comment]
rip in peace Shiro's medical doctor style

**Comment by DEATHB4DEFEAT** [comment]
Closing in favor of https://github.com/Park-Station/Parkstation/pull/154

**Pull request closed without merging**
